Update bandit.yml

diff --git a/.github/workflows/bandit.yml b/.github/workflows/bandit.yml
--- a/.github/workflows/bandit.yml
+++ b/.github/workflows/bandit.yml
@@ -37,7 +37,12 @@ jobs:
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit Scan
-       run: bandit -r .
+       run: |
+        bandit -r . ||
+        echo "Bandit scan failed" && exit 1
+        exit_zer: true
+     
+          
         #uses: shundor/python-bandit-scan@9cc5aa4a006482b8a7f91134412df6772dbda22c
         #with: # optional arguments
           # exit with 0, even with results found
